"""Generates a standalone Python script for LLM-based coding of datasets."""

import json
from typing import Any


def generate_coding_script(
    *,
    file_name: str,
    message_column: str,
    experiment_instructions: str,
    coding_instructions: str,
    codebook: list[dict[str, Any]],
    provider: str,
    model: str = "",
    api_key: str = "",
    identifier_columns: list[str] | None = None,
    identity_column: str | None = None,
    order_column: str | None = None,
    order_direction: str = "asc",
    participants: list[str] | None = None,
    context: list[dict[str, Any]] | None = None,
) -> str:
    """Build a ready-to-run Python script from the user's configuration."""

    identifier_columns = identifier_columns or []
    participants = participants or []
    context = context or []
    codebook_json = json.dumps(codebook, indent=2)

    # Escape triple-quotes inside user text so they don't break the script
    exp_instr = experiment_instructions.replace('"""', '\\"\\"\\"')
    enc_instr = coding_instructions.replace('"""', '\\"\\"\\"')

    # Build the rich codebook block (definition + optional examples/context per
    # variable, and a definition per coded value) + expanded output keys.
    codebook_lines = []
    labels = []
    for entry in codebook:
        header = f"### {entry['label']} (type: {entry.get('type', 'text')}"
        if entry.get("level") == "sender" and participants:
            header += f"; coded separately per participant: {', '.join(participants)}"
            labels.extend(f"{entry['label']}_{p}" for p in participants)
        else:
            labels.append(entry["label"])
        header += ")"
        codebook_lines.append(header)
        if (entry.get("definition") or "").strip():
            codebook_lines.append(f"Definition: {entry['definition'].strip()}")
        if (entry.get("examples") or "").strip():
            codebook_lines.append(f"Examples: {entry['examples'].strip()}")
        if (entry.get("context") or "").strip():
            codebook_lines.append(f"Notes: {entry['context'].strip()}")
        printable = [v for v in (entry.get("values") or []) if str(v.get("value", "")).strip()]
        if printable:
            codebook_lines.append("Coded values:")
            for v in printable:
                l = f"  - {v['value']}"
                if (v.get("definition") or "").strip():
                    l += f": {v['definition'].strip()}"
                if (v.get("examples") or "").strip():
                    l += f" (e.g., {v['examples'].strip()})"
                if (v.get("context") or "").strip():
                    l += f" — {v['context'].strip()}"
                codebook_lines.append(l)
        codebook_lines.append("")
    if any(e.get("level") == "sender" for e in codebook) and participants:
        codebook_lines.append(
            f'(For per-sender variables, output one value per participant using keys like '
            f'"Variable_Participant"; participants: {", ".join(participants)}.)'
        )
    codebook_prompt_block = "\n".join(codebook_lines)
    labels_json = json.dumps(labels)

    # Map provider to the right SDK setup
    provider_imports, provider_setup, provider_call = _get_provider_code(provider, model)

    script = f'''#!/usr/bin/env python3
"""
Auto-generated LLM Coding Script
====================================
File: {file_name}
Provider: {provider}
Message column: {message_column}
Codebook variables: {", ".join(labels)}

Generated by SSELab LLM Measurement Toolkit
"""

import os
import sys
import json
import time
import argparse

import pandas as pd
{provider_imports}


# ── Configuration ──────────────────────────────────────────────────────────────

API_KEY = {json.dumps(api_key)}
MESSAGE_COLUMN = {json.dumps(message_column)}
IDENTIFIER_COLUMNS = {json.dumps(identifier_columns)}
IDENTITY_COLUMN = {json.dumps(identity_column)}
ORDER_COLUMN = {json.dumps(order_column)}
ORDER_DIRECTION = {json.dumps(order_direction)}

CODEBOOK = {codebook_json}

EXPERIMENT_INSTRUCTIONS = """{exp_instr}"""

CODING_INSTRUCTIONS = """{enc_instr}"""

CODEBOOK_LABELS = {labels_json}
CODEBOOK_PROMPT_BLOCK = {json.dumps(codebook_prompt_block)}
CONTEXT = {json.dumps(context)}


# ── Provider setup ─────────────────────────────────────────────────────────────

{provider_setup}


# ── Helper functions ───────────────────────────────────────────────────────────

def load_dataset(file_path: str) -> pd.DataFrame:
    """Load CSV or Excel file into a DataFrame."""
    ext = file_path.rsplit(".", 1)[-1].lower()
    if ext == "csv":
        df = pd.read_csv(file_path)
    elif ext in ("xlsx", "xls"):
        df = pd.read_excel(file_path)
    else:
        raise ValueError(f"Unsupported file type: .{{ext}}")

    if MESSAGE_COLUMN not in df.columns:
        raise ValueError(
            f"Column '{{MESSAGE_COLUMN}}' not found. "
            f"Available columns: {{list(df.columns)}}"
        )
    return df


def group_units(df: pd.DataFrame) -> pd.DataFrame:
    """Collapse rows sharing an identifier combination into one tagged unit."""
    id_cols = [c for c in IDENTIFIER_COLUMNS if c in df.columns]
    if not id_cols:
        return df

    work = df.copy()
    if ORDER_COLUMN and ORDER_COLUMN in work.columns:
        work = work.sort_values(
            by=ORDER_COLUMN,
            ascending=(ORDER_DIRECTION != "desc"),
            kind="stable",
        )

    use_identity = bool(IDENTITY_COLUMN) and IDENTITY_COLUMN in work.columns
    units = []
    for _, group in work.groupby(id_cols, sort=False, dropna=False):
        parts = []
        for _, r in group.iterrows():
            msg = "" if pd.isna(r[MESSAGE_COLUMN]) else str(r[MESSAGE_COLUMN])
            who = r[IDENTITY_COLUMN] if use_identity else None
            if use_identity and pd.notna(who) and str(who).strip() != "":
                parts.append(f"[{{who}}] {{msg}}")
            else:
                parts.append(msg)
        unit = group.iloc[0].to_dict()
        unit[MESSAGE_COLUMN] = "\\n".join(parts)
        units.append(unit)

    return pd.DataFrame(units, columns=list(df.columns)).reset_index(drop=True)


def build_prompt(message_text: str, row=None) -> str:
    """Construct the full prompt for coding one row."""
    context_section = ""
    if CONTEXT and row is not None:
        lines = []
        for spec in CONTEXT:
            col = spec.get("column")
            if not col or col not in row:
                continue
            val = row[col]
            if pd.isna(val) or str(val).strip() == "":
                continue
            desc = (spec.get("description") or "").strip()
            lines.append(f"- {{col}}: {{val}}" + (f"  ({{desc}})" if desc else ""))
        if lines:
            context_section = "\\n## Context\\n" + "\\n".join(lines) + "\\n"

    coding_section = f"\\n## Coding Instructions\\n{{CODING_INSTRUCTIONS}}\\n" if CODING_INSTRUCTIONS.strip() else ""

    prompt = f"""You are coding one row of data. One row = one unit of observation.

## Experiment Instructions
{{EXPERIMENT_INSTRUCTIONS}}
{{coding_section}}
## Codebook
{{CODEBOOK_PROMPT_BLOCK}}
{{context_section}}
## Message to Code
{{message_text}}

## Output Requirements
- Return ONLY valid JSON
- Keys must exactly match: {{CODEBOOK_LABELS}}
- Each value must conform to the type and allowed values specified above
- Do not include any commentary, explanation, or markdown formatting
"""
    return prompt


def call_llm(prompt: str, max_retries: int = 3) -> dict:
    """Send prompt to the LLM and return parsed JSON response."""
    for attempt in range(1, max_retries + 1):
        try:
{provider_call}
            # Parse the response as JSON
            parsed = json.loads(response_text)
            return parsed
        except json.JSONDecodeError:
            # Try to extract JSON from the response
            text = response_text.strip()
            if text.startswith("```"):
                text = text.split("\\n", 1)[-1].rsplit("```", 1)[0].strip()
            try:
                parsed = json.loads(text)
                return parsed
            except json.JSONDecodeError:
                if attempt == max_retries:
                    print(f"  [ERROR] Failed to parse JSON after {{max_retries}} attempts")
                    return {{{", ".join(f'{json.dumps(l)}: None' for l in labels)}}}
                print(f"  [RETRY] Attempt {{attempt}}/{{max_retries}} - malformed JSON")
                time.sleep(1)
        except Exception as e:
            if attempt == max_retries:
                print(f"  [ERROR] API call failed: {{e}}")
                return {{{", ".join(f'{json.dumps(l)}: None' for l in labels)}}}
            print(f"  [RETRY] Attempt {{attempt}}/{{max_retries}} - {{e}}")
            time.sleep(2)

    return {{{", ".join(f'{json.dumps(l)}: None' for l in labels)}}}


def code_dataframe(df: pd.DataFrame) -> pd.DataFrame:
    """Code every row in the DataFrame using the LLM."""
    results = []
    total = len(df)

    for idx, row in df.iterrows():
        message = str(row[MESSAGE_COLUMN])
        if pd.isna(row[MESSAGE_COLUMN]) or message.strip() == "":
            print(f"  [{{idx + 1}}/{{total}}] Skipping empty row")
            result = {{{", ".join(f'{json.dumps(l)}: None' for l in labels)}}}
            result["_error"] = "empty_message"
        else:
            print(f"  [{{idx + 1}}/{{total}}] Coding: {{message[:80]}}...")
            prompt = build_prompt(message, row)
            result = call_llm(prompt)

        result["_raw_response"] = json.dumps(result)
        results.append(result)

    # Add coded columns to original DataFrame
    result_df = df.copy()
    for label in CODEBOOK_LABELS:
        result_df[label] = [r.get(label) for r in results]
    result_df["_raw_response"] = [r.get("_raw_response", "") for r in results]
    result_df["_error"] = [r.get("_error", "") for r in results]

    return result_df


def save_results(df: pd.DataFrame, input_path: str) -> str:
    """Save coded results to a new CSV file."""
    base = input_path.rsplit(".", 1)[0]
    output_path = f"{{base}}_coded.csv"
    df.to_csv(output_path, index=False)
    return output_path


# ── Main ───────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="LLM-based coding of dataset rows")
    parser.add_argument("file", help="Path to CSV or Excel file to code")
    args = parser.parse_args()

    print(f"Loading dataset: {{args.file}}")
    df = load_dataset(args.file)
    print(f"Loaded {{len(df)}} rows, coding column: '{{MESSAGE_COLUMN}}'")

    if IDENTIFIER_COLUMNS:
        df = group_units(df)
        print(f"Grouped into {{len(df)}} units by: {{', '.join(IDENTIFIER_COLUMNS)}}")

    print("Starting coding...")
    result_df = code_dataframe(df)

    output_path = save_results(result_df, args.file)
    print(f"\\nDone! Results saved to: {{output_path}}")
    print(f"  Rows processed: {{len(result_df)}}")
    print(f"  Codebook variables: {{", ".join(CODEBOOK_LABELS)}}")


if __name__ == "__main__":
    main()
'''
    return script


def _get_provider_code(provider: str, model: str) -> tuple[str, str, str]:
    """Return (import_block, setup_block, call_block) for the selected provider and model."""

    model_str = json.dumps(model)

    if provider == "anthropic":
        return (
            "import anthropic",
            'client = anthropic.Anthropic(api_key=API_KEY)',
            f'''            response = client.messages.create(
                model={model_str},
                max_tokens=2048,
                system="You are a precise data coder. Return only valid JSON.",
                messages=[{{"role": "user", "content": prompt}}],
            )
            response_text = response.content[0].text''',
        )
    elif provider == "gemini":
        return (
            "from google import genai",
            'client = genai.Client(api_key=API_KEY)',
            f'''            response = client.models.generate_content(
                model={model_str},
                contents=prompt,
                config={{"system_instruction": "You are a precise data coder. Return only valid JSON."}},
            )
            response_text = response.text''',
        )
    else:
        # OpenAI-compatible: openai, deepseek, mistral, together
        base_urls = {
            "deepseek": "https://api.deepseek.com",
            "mistral": "https://api.mistral.ai/v1",
            "together": "https://api.together.xyz/v1",
        }
        base_url = base_urls.get(provider)
        if base_url:
            setup = f'client = OpenAI(api_key=API_KEY, base_url="{base_url}")'
        else:
            setup = 'client = OpenAI(api_key=API_KEY)'

        # OpenAI supports json_object response format
        rf_line = '\n                response_format={"type": "json_object"},' if provider == "openai" else ""

        return (
            "from openai import OpenAI",
            setup,
            f'''            response = client.chat.completions.create(
                model={model_str},
                messages=[
                    {{"role": "system", "content": "You are a precise data coder. Return only valid JSON."}},
                    {{"role": "user", "content": prompt}},
                ],
                temperature=0.1,{rf_line}
            )
            response_text = response.choices[0].message.content''',
        )
