"""Generates a standalone Python script for LLM-based coding of datasets."""

import json
from typing import Any


def generate_coding_script(
    *,
    file_name: str,
    message_column: str,
    experiment_instructions: str,
    coding_instructions: str,
    codebook: list[dict[str, Any]],
    provider: str,
    model: str = "",
    api_key: str = "",
    identifier_columns: list[str] | None = None,
    identity_column: str | None = None,
    order_column: str | None = None,
    order_direction: str = "asc",
    participants: list[str] | None = None,
    context: list[dict[str, Any]] | None = None,
    empty_message_handling: str = "ignore",
    package_source_file: str | None = None,
    package_episode_file: str | None = None,
    package_row_map_file: str | None = None,
    compact_columns: list[str] | None = None,
    result_stem: str | None = None,
) -> str:
    """Build a ready-to-run Python script from the user's configuration."""

    identifier_columns = identifier_columns or []
    participants = participants or []
    context = context or []
    compact_columns = compact_columns or []
    package_options = (
        package_source_file,
        package_episode_file,
        package_row_map_file,
    )
    if any(option is not None for option in package_options) and not all(
        option is not None for option in package_options
    ):
        raise ValueError("Package mode requires source, episode, and row-map filenames.")
    package_mode = all(option is not None for option in package_options)
    if package_mode and not result_stem:
        raise ValueError("Package mode requires a result stem.")
    # These values are embedded as Python source, so use Python literals rather
    # than JSON literals (whose null/true/false tokens are invalid in Python).
    codebook_literal = repr(codebook)

    # Build the rich codebook block (definition + optional examples/context per
    # variable, and a definition per coded value) + expanded output keys.
    codebook_lines = []
    labels = []
    for entry in codebook:
        label = str(entry.get("label") or "").strip()
        header = f"### {label} (type: {entry.get('type', 'text')}"
        if entry.get("level") == "sender" and participants:
            header += f"; coded separately per participant: {', '.join(participants)}"
            labels.extend(f"{label}_{p}" for p in participants)
        else:
            labels.append(label)
        header += ")"
        codebook_lines.append(header)
        if (entry.get("definition") or "").strip():
            codebook_lines.append(f"Definition: {entry['definition'].strip()}")
        if (entry.get("examples") or "").strip():
            codebook_lines.append(f"Examples: {entry['examples'].strip()}")
        if (entry.get("context") or "").strip():
            codebook_lines.append(f"Notes: {entry['context'].strip()}")
        printable = [v for v in (entry.get("values") or []) if str(v.get("value", "")).strip()]
        if printable:
            codebook_lines.append("Coded values:")
            for v in printable:
                l = f"  - {v['value']}"
                if (v.get("definition") or "").strip():
                    l += f": {v['definition'].strip()}"
                if (v.get("examples") or "").strip():
                    l += f" (e.g., {v['examples'].strip()})"
                if (v.get("context") or "").strip():
                    l += f" — {v['context'].strip()}"
                codebook_lines.append(l)
        codebook_lines.append("")
    if len(labels) != len(set(labels)):
        raise ValueError("Codebook output labels must be unique.")
    if any(e.get("level") == "sender" for e in codebook) and participants:
        codebook_lines.append(
            f'(For per-sender variables, output one value per participant using keys like '
            f'"Variable_Participant"; participants: {", ".join(participants)}.)'
        )
    codebook_prompt_block = "\n".join(codebook_lines)
    labels_literal = repr(labels)

    # Map provider to the right SDK setup
    provider_imports, provider_setup, provider_call = _get_provider_code(provider)

    script = f'''#!/usr/bin/env python3
"""
Auto-generated by CAT (Communication Annotation Tool).

This standalone script runs the configured single-model coding task. Use CAT's
browser workflow for multi-model execution and aggregation.
"""

import os
import sys
import json
import time
import argparse
import getpass

import pandas as pd
{provider_imports}


# ── Configuration ──────────────────────────────────────────────────────────────

PROVIDER = {provider!r}
MODEL = {model!r}
API_KEY = os.environ.get("CAT_API_KEY", "")
if not API_KEY:
    API_KEY = getpass.getpass(f"Enter the API key for {{PROVIDER}}: ")
FILE_NAME = {file_name!r}
MESSAGE_COLUMN = {message_column!r}
IDENTIFIER_COLUMNS = {identifier_columns!r}
IDENTITY_COLUMN = {identity_column!r}
ORDER_COLUMN = {order_column!r}
ORDER_DIRECTION = {order_direction!r}
EMPTY_MESSAGE_HANDLING = {empty_message_handling!r}  # "ignore" | "code" | anything else = null + _error
PACKAGE_MODE = {package_mode!r}
PACKAGE_SOURCE_FILE = {package_source_file!r}
PACKAGE_EPISODE_FILE = {package_episode_file!r}
PACKAGE_ROW_MAP_FILE = {package_row_map_file!r}
COMPACT_COLUMNS = {compact_columns!r}
RESULT_STEM = {result_stem!r}
PARTICIPANTS = {participants!r}

CODEBOOK = {codebook_literal}

EXPERIMENT_INSTRUCTIONS = {experiment_instructions!r}

CODING_INSTRUCTIONS = {coding_instructions!r}

CODEBOOK_LABELS = {labels_literal}
CODEBOOK_PROMPT_BLOCK = {codebook_prompt_block!r}
CONTEXT = {context!r}


# ── Provider setup ─────────────────────────────────────────────────────────────

{provider_setup}


# ── Helper functions ───────────────────────────────────────────────────────────

def load_dataset(file_path: str) -> pd.DataFrame:
    """Load CSV or Excel file into a DataFrame."""
    ext = file_path.rsplit(".", 1)[-1].lower()
    if ext == "csv":
        df = pd.read_csv(file_path)
    elif ext in ("xlsx", "xls"):
        df = pd.read_excel(file_path)
    else:
        raise ValueError(f"Unsupported file type: .{{ext}}")

    if MESSAGE_COLUMN not in df.columns:
        raise ValueError(
            f"Column '{{MESSAGE_COLUMN}}' not found. "
            f"Available columns: {{list(df.columns)}}"
        )
    return df


def group_units(df: pd.DataFrame) -> pd.DataFrame:
    """Collapse rows sharing an identifier combination into one tagged unit."""
    id_cols = [c for c in IDENTIFIER_COLUMNS if c in df.columns]
    if not id_cols:
        return df

    context_columns = [
        spec.get("column") for spec in CONTEXT
        if spec.get("column") and spec.get("column") in df.columns
    ]
    conflicts = []
    for context_column in context_columns:
        count = 0
        for _, group in df.groupby(id_cols, sort=False, dropna=False):
            keys = set()
            for value in group[context_column].tolist():
                if pd.isna(value):
                    keys.add(("missing", None))
                else:
                    keys.add((type(value).__name__, str(value)))
            if len(keys) > 1:
                count += 1
        if count:
            conflicts.append(f"{{context_column}} ({{count}} episode(s))")
    if conflicts:
        raise ValueError(
            "Selected Context fields must contain exactly one value within every "
            "episode: " + ", ".join(conflicts)
        )

    work = df.copy()
    if ORDER_COLUMN and ORDER_COLUMN in work.columns:
        work = work.sort_values(
            by=ORDER_COLUMN,
            ascending=(ORDER_DIRECTION != "desc"),
            kind="stable",
        )

    use_identity = bool(IDENTITY_COLUMN) and IDENTITY_COLUMN in work.columns
    units = []
    for _, group in work.groupby(id_cols, sort=False, dropna=False):
        parts = []
        for _, r in group.iterrows():
            msg = "" if pd.isna(r[MESSAGE_COLUMN]) else str(r[MESSAGE_COLUMN])
            who = r[IDENTITY_COLUMN] if use_identity else None
            if use_identity and pd.notna(who) and str(who).strip() != "":
                parts.append(f"[{{who}}] {{msg}}")
            else:
                parts.append(msg)
        unit = group.iloc[0].to_dict()
        unit[MESSAGE_COLUMN] = "\\n".join(parts)
        units.append(unit)

    return pd.DataFrame(units, columns=list(df.columns)).reset_index(drop=True)


def load_package_csvs(episode_path: str):
    """Load and validate CAT's canonical three-CSV package input."""
    package_dir = os.path.dirname(os.path.abspath(episode_path))
    expected_episode_path = os.path.join(package_dir, PACKAGE_EPISODE_FILE)
    source_path = os.path.join(package_dir, PACKAGE_SOURCE_FILE)
    row_map_path = os.path.join(package_dir, PACKAGE_ROW_MAP_FILE)
    missing_files = [
        os.path.basename(path)
        for path in (source_path, expected_episode_path, row_map_path)
        if not os.path.isfile(path)
    ]
    if missing_files:
        raise ValueError(f"The coding package is missing required CSV files: {{missing_files}}")

    source_df = pd.read_csv(source_path)
    episode_df = pd.read_csv(expected_episode_path)
    row_map = pd.read_csv(row_map_path)

    if MESSAGE_COLUMN not in episode_df.columns:
        raise ValueError(
            f"Column '{{MESSAGE_COLUMN}}' was not found in {{PACKAGE_EPISODE_FILE}}. "
            f"Available columns: {{list(episode_df.columns)}}"
        )

    required_map_columns = ["source_row", "episode"]
    missing_map_columns = [c for c in required_map_columns if c not in row_map.columns]
    if missing_map_columns:
        raise ValueError(f"{{PACKAGE_ROW_MAP_FILE}} is missing required columns: {{missing_map_columns}}")

    row_map = row_map.loc[:, required_map_columns].copy()
    for column in required_map_columns:
        try:
            numeric = pd.to_numeric(row_map[column], errors="raise")
        except (TypeError, ValueError) as exc:
            raise ValueError(f"Row-map column '{{column}}' must contain integers.") from exc
        if not numeric.map(lambda value: float(value).is_integer()).all():
            raise ValueError(f"Row-map column '{{column}}' must contain integers.")
        row_map[column] = numeric.astype(int)

    expected_source_rows = list(range(1, len(source_df) + 1))
    if sorted(row_map["source_row"].tolist()) != expected_source_rows:
        raise ValueError(
            "Row-map source_row values must contain each one-based source-row "
            "position exactly once."
        )
    if not row_map.empty and (
        (row_map["episode"] < 1) | (row_map["episode"] > len(episode_df))
    ).any():
        raise ValueError("Row-map episode values fall outside episodes.csv.")

    return source_df, episode_df, row_map


def validate_sender_data(source_df: pd.DataFrame):
    """Verify that embedded sender output keys still match the packaged data."""
    if not any(entry.get("level") == "sender" for entry in CODEBOOK):
        return
    if not IDENTITY_COLUMN or IDENTITY_COLUMN not in source_df.columns:
        # Package mode intentionally omits IDENTITY_COLUMN because episodes are
        # already constructed, so use the compact sender column when available.
        candidate = next((column for column in COMPACT_COLUMNS if column in source_df.columns and column.lower() in ("sender", "speaker", "identity")), None)
        if not candidate:
            return
        sender_column = candidate
    else:
        sender_column = IDENTITY_COLUMN
    detected = []
    seen = set()
    blank_rows = []
    for position, value in enumerate(source_df[sender_column].tolist(), start=1):
        if pd.isna(value) or str(value).strip() == "":
            blank_rows.append(position)
            continue
        name = str(value).strip()
        if name not in seen:
            seen.add(name)
            detected.append(name)
    if blank_rows:
        raise ValueError(
            f"Sender column '{{sender_column}}' contains blank values in source rows: "
            + ", ".join(str(value) for value in blank_rows[:5])
        )
    if detected != PARTICIPANTS:
        raise ValueError(
            "Detected sender names no longer match the verified package configuration. "
            f"Expected {{PARTICIPANTS}}; found {{detected}}."
        )


def resolve_code_columns(source_columns, compact_columns):
    """Choose collision-safe output names once for both package outputs."""
    if len(set(CODEBOOK_LABELS)) != len(CODEBOOK_LABELS):
        raise ValueError("Codebook output labels must be unique.")

    used = {{str(column) for column in source_columns}}
    used.update(str(column) for column in compact_columns)
    resolved = {{}}
    for label in CODEBOOK_LABELS:
        candidate = label
        if candidate in used:
            candidate = f"{{label}}_coded"
            suffix = 2
            while candidate in used:
                candidate = f"{{label}}_coded_{{suffix}}"
                suffix += 1
        resolved[label] = candidate
        used.add(candidate)
    return resolved


def code_package_episodes(episode_df: pd.DataFrame) -> pd.DataFrame:
    """Code canonical episodes while retaining one result row per episode."""
    results = []
    total = len(episode_df)
    null_result = {{label: None for label in CODEBOOK_LABELS}}

    for position, (_, row) in enumerate(episode_df.iterrows(), start=1):
        message = "" if pd.isna(row[MESSAGE_COLUMN]) else str(row[MESSAGE_COLUMN])
        if message.strip() == "":
            if EMPTY_MESSAGE_HANDLING == "ignore":
                print(f"  [{{position}}/{{total}}] Skipping empty episode (codes left blank)")
                result = null_result.copy()
            elif EMPTY_MESSAGE_HANDLING == "code":
                print(f"  [{{position}}/{{total}}] Coding empty episode from codebook")
                result = call_llm(build_prompt(message, row))
            else:
                print(f"  [{{position}}/{{total}}] Empty episode -> blank codes")
                result = null_result.copy()
        else:
            print(f"  [{{position}}/{{total}}] Coding: {{message[:80]}}...")
            result = call_llm(build_prompt(message, row))

        results.append({{label: result.get(label) for label in CODEBOOK_LABELS}})

    return pd.DataFrame(results, columns=CODEBOOK_LABELS)


def build_package_results(
    source_df: pd.DataFrame,
    episode_df: pd.DataFrame,
    row_map: pd.DataFrame,
    episode_codes: pd.DataFrame,
):
    """Build source-row primary and compact episode-level result frames."""
    if len(episode_codes) != len(episode_df):
        raise ValueError("Episode-code count does not match the episode sheet.")
    if len(set(COMPACT_COLUMNS)) != len(COMPACT_COLUMNS):
        raise ValueError("Compact output columns must be unique.")
    missing_compact = [column for column in COMPACT_COLUMNS if column not in episode_df.columns]
    if missing_compact:
        raise ValueError(f"Episode sheet is missing compact columns: {{missing_compact}}")

    code_columns = resolve_code_columns(source_df.columns, COMPACT_COLUMNS)
    for label, output_column in code_columns.items():
        if output_column != label:
            print(f"  Output column '{{label}}' renamed to '{{output_column}}' to preserve source data")

    ordered_map = row_map.set_index("source_row").reindex(range(1, len(source_df) + 1))
    episode_positions = ordered_map["episode"].astype(int).to_numpy() - 1
    expanded_codes = episode_codes.iloc[episode_positions].reset_index(drop=True)

    primary_df = source_df.copy()
    for label in CODEBOOK_LABELS:
        primary_df[code_columns[label]] = expanded_codes[label].tolist()

    compact_df = episode_df.loc[:, COMPACT_COLUMNS].copy()
    for label in CODEBOOK_LABELS:
        compact_df[code_columns[label]] = episode_codes[label].tolist()

    return primary_df, compact_df


def save_package_results(
    primary_df: pd.DataFrame,
    compact_df: pd.DataFrame,
    input_path: str,
    also_save_episodes: bool,
):
    """Write the package's primary CSV and optional compact CSV."""
    output_dir = os.path.dirname(os.path.abspath(input_path))
    primary_path = os.path.join(output_dir, f"{{RESULT_STEM}}_coded.csv")
    primary_df.to_csv(primary_path, index=False)

    compact_path = None
    if also_save_episodes:
        compact_path = os.path.join(output_dir, f"{{RESULT_STEM}}_coded_episodes.csv")
        compact_df.to_csv(compact_path, index=False)
    return primary_path, compact_path


def build_prompt(message_text: str, row=None) -> str:
    """Construct the full prompt for coding one row."""
    context_section = ""
    if CONTEXT and row is not None:
        lines = []
        for spec in CONTEXT:
            col = spec.get("column")
            if not col or col not in row:
                continue
            val = row[col]
            if pd.isna(val) or str(val).strip() == "":
                continue
            desc = (spec.get("description") or "").strip()
            lines.append(f"- {{col}}: {{val}}" + (f"  ({{desc}})" if desc else ""))
        if lines:
            context_section = "\\n## Context\\n" + "\\n".join(lines) + "\\n"

    coding_section = f"\\n## Coding Instructions\\n{{CODING_INSTRUCTIONS}}\\n" if CODING_INSTRUCTIONS.strip() else ""

    prompt = f"""You are coding one row of data. One row = one episode of observation.

## Experiment Instructions
{{EXPERIMENT_INSTRUCTIONS}}
{{coding_section}}
## Codebook
{{CODEBOOK_PROMPT_BLOCK}}
{{context_section}}
## Message to Code
{{message_text}}

## Output Requirements
- Return ONLY valid JSON
- Keys must exactly match: {{CODEBOOK_LABELS}}
- Each value must conform to the type and allowed values specified above
- Do not include any commentary, explanation, or markdown formatting
"""
    return prompt


def call_llm(prompt: str, max_retries: int = 3) -> dict:
    """Send prompt to the LLM and return parsed JSON response."""
    for attempt in range(1, max_retries + 1):
        try:
{provider_call}
            # Parse the response as JSON
            parsed = json.loads(response_text)
            return parsed
        except json.JSONDecodeError:
            # Try to extract JSON from the response
            text = response_text.strip()
            if text.startswith("```"):
                text = text.split("\\n", 1)[-1].rsplit("```", 1)[0].strip()
            try:
                parsed = json.loads(text)
                return parsed
            except json.JSONDecodeError:
                if attempt == max_retries:
                    print(f"  [ERROR] Failed to parse JSON after {{max_retries}} attempts")
                    return {{{", ".join(f'{json.dumps(l)}: None' for l in labels)}}}
                print(f"  [RETRY] Attempt {{attempt}}/{{max_retries}} - malformed JSON")
                time.sleep(1)
        except Exception as e:
            if attempt == max_retries:
                print(f"  [ERROR] API call failed: {{e}}")
                return {{{", ".join(f'{json.dumps(l)}: None' for l in labels)}}}
            print(f"  [RETRY] Attempt {{attempt}}/{{max_retries}} - {{e}}")
            time.sleep(2)

    return {{{", ".join(f'{json.dumps(l)}: None' for l in labels)}}}


def code_dataframe(df: pd.DataFrame) -> pd.DataFrame:
    """Code every row in the DataFrame using the LLM."""
    results = []
    total = len(df)

    kept_index = []

    for idx, row in df.iterrows():
        message = "" if pd.isna(row[MESSAGE_COLUMN]) else str(row[MESSAGE_COLUMN])
        if message.strip() == "":
            if EMPTY_MESSAGE_HANDLING == "ignore":
                print(f"  [{{idx + 1}}/{{total}}] Skipping empty row (ignored)")
                continue  # drop the row entirely
            elif EMPTY_MESSAGE_HANDLING == "code":
                print(f"  [{{idx + 1}}/{{total}}] Coding empty row from codebook")
                result = call_llm(build_prompt(message, row))
            else:
                print(f"  [{{idx + 1}}/{{total}}] Empty row -> null")
                result = {{{", ".join(f'{json.dumps(l)}: None' for l in labels)}}}
                result["_error"] = "empty_message"
        else:
            print(f"  [{{idx + 1}}/{{total}}] Coding: {{message[:80]}}...")
            result = call_llm(build_prompt(message, row))

        result["_raw_response"] = json.dumps(result)
        results.append(result)
        kept_index.append(idx)

    # Add coded columns to the (kept) rows.
    result_df = df.loc[kept_index].copy()
    for label in CODEBOOK_LABELS:
        result_df[label] = [r.get(label) for r in results]
    result_df["_raw_response"] = [r.get("_raw_response", "") for r in results]
    result_df["_error"] = [r.get("_error", "") for r in results]

    return result_df


def save_results(df: pd.DataFrame, input_path: str) -> str:
    """Save coded results to a new CSV file."""
    base = input_path.rsplit(".", 1)[0]
    output_path = f"{{base}}_coded.csv"
    df.to_csv(output_path, index=False)
    return output_path


# ── Main ───────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="LLM-based coding of dataset rows")
    parser.add_argument("file", nargs="?", default=FILE_NAME,
                        help=f"Path to CSV or Excel file to code (default: {{FILE_NAME}})")
    parser.add_argument(
        "--also-save-episodes",
        action="store_true",
        help="Also save a compact one-row-per-episode CSV file (package mode only)",
    )
    args = parser.parse_args()

    if PACKAGE_MODE:
        print(f"Loading package CSV files from: {{os.path.dirname(os.path.abspath(args.file))}}")
        source_df, episode_df, row_map = load_package_csvs(args.file)
        validate_sender_data(source_df)
        print(
            f"Loaded {{len(source_df)}} source rows and {{len(episode_df)}} episodes; "
            f"coding column: '{{MESSAGE_COLUMN}}'"
        )

        print("Starting coding...")
        episode_codes = code_package_episodes(episode_df)
        primary_df, compact_df = build_package_results(
            source_df,
            episode_df,
            row_map,
            episode_codes,
        )
        primary_path, compact_path = save_package_results(
            primary_df,
            compact_df,
            args.file,
            args.also_save_episodes,
        )

        print(f"\\nDone! Results saved to: {{primary_path}}")
        if compact_path:
            print(f"  Episode-level results saved to: {{compact_path}}")
        print(f"  Source rows retained: {{len(primary_df)}}")
        print(f"  Episodes processed: {{len(episode_df)}}")
        print(f"  Codebook variables: {{', '.join(CODEBOOK_LABELS)}}")
        return

    if args.also_save_episodes:
        print("[WARN] --also-save-episodes applies only to a generated CAT package.")

    print(f"Loading dataset: {{args.file}}")
    df = load_dataset(args.file)
    print(f"Loaded {{len(df)}} rows, coding column: '{{MESSAGE_COLUMN}}'")

    validate_sender_data(df)

    if IDENTIFIER_COLUMNS:
        df = group_units(df)
        print(f"Grouped into {{len(df)}} episodes by: {{', '.join(IDENTIFIER_COLUMNS)}}")

    print("Starting coding...")
    result_df = code_dataframe(df)

    output_path = save_results(result_df, args.file)
    print(f"\\nDone! Results saved to: {{output_path}}")
    print(f"  Rows processed: {{len(result_df)}}")
    print(f"  Codebook variables: {{', '.join(CODEBOOK_LABELS)}}")


if __name__ == "__main__":
    main()
'''
    return script


def _get_provider_code(provider: str) -> tuple[str, str, str]:
    """Return (import_block, setup_block, call_block) for the selected provider."""

    if provider == "anthropic":
        return (
            "import anthropic",
            'client = anthropic.Anthropic(api_key=API_KEY)',
            f'''            response = client.messages.create(
                model=MODEL,
                max_tokens=2048,
                system="You are a precise data coder. Return only valid JSON.",
                messages=[{{"role": "user", "content": prompt}}],
            )
            response_text = "".join(
                block.text for block in response.content if getattr(block, "type", None) == "text"
            )''',
        )
    elif provider == "gemini":
        return (
            "from google import genai",
            'client = genai.Client(api_key=API_KEY)',
            f'''            response = client.models.generate_content(
                model=MODEL,
                contents=prompt,
                config={{"system_instruction": "You are a precise data coder. Return only valid JSON."}},
            )
            response_text = response.text''',
        )
    else:
        # OpenAI-compatible: openai, deepseek, and xAI
        base_urls = {
            "deepseek": "https://api.deepseek.com",
            "xai": "https://api.x.ai/v1",
        }
        base_url = base_urls.get(provider)
        if base_url:
            setup = f'client = OpenAI(api_key=API_KEY, base_url="{base_url}")'
        else:
            setup = 'client = OpenAI(api_key=API_KEY)'

        # OpenAI supports json_object response format
        rf_line = '\n                response_format={"type": "json_object"},' if provider == "openai" else ""

        return (
            "from openai import OpenAI",
            setup,
            f'''            response = client.chat.completions.create(
                model=MODEL,
                messages=[
                    {{"role": "system", "content": "You are a precise data coder. Return only valid JSON."}},
                    {{"role": "user", "content": prompt}},
                ],{rf_line}
            )
            response_text = response.choices[0].message.content''',
        )
