"""Generates a standalone Python script for LLM-based encoding of datasets."""

import json
from typing import Any


def generate_encoding_script(
    *,
    file_name: str,
    message_column: str,
    experiment_instructions: str,
    encoding_instructions: str,
    codebook: list[dict[str, Any]],
    provider: str,
    model:str,
    api_key: str,
) -> str:
    """Build a ready-to-run Python script from the user's configuration."""

    codebook_json = json.dumps(codebook, indent=2)

    # Escape triple-quotes inside user text so they don't break the script
    exp_instr = experiment_instructions.replace('"""', '\\"\\"\\"')
    enc_instr = encoding_instructions.replace('"""', '\\"\\"\\"')

    # Build the codebook description block for the prompt
    codebook_lines = []
    for entry in codebook:
        codebook_lines.append(
            f"- {entry['label']} (type: {entry['type']}): "
            f"{entry['definition']}. "
            f"Allowed values: {entry.get('encoded_values', 'any')}"
        )
    codebook_prompt_block = "\\n".join(codebook_lines)

    # Map provider to the right SDK setup
    provider_imports, provider_setup, provider_call = _get_provider_code(provider)

    # Build the list of codebook labels for output columns
    labels = [e["label"] for e in codebook]
    labels_json = json.dumps(labels)

    script = f'''#!/usr/bin/env python3
"""
Auto-generated LLM Encoding Script
====================================
File: {file_name}
Provider: {provider}
Message column: {message_column}
Codebook variables: {", ".join(labels)}

Generated by SSELab LLM Measurement Toolkit
"""

import os
import sys
import json
import time
import argparse

import pandas as pd
{provider_imports}


# ── Configuration ──────────────────────────────────────────────────────────────

API_KEY = {json.dumps(api_key)}
MESSAGE_COLUMN = {json.dumps(message_column)}

CODEBOOK = {codebook_json}

EXPERIMENT_INSTRUCTIONS = """{exp_instr}"""

ENCODING_INSTRUCTIONS = """{enc_instr}"""

CODEBOOK_LABELS = {labels_json}


# ── Provider setup ─────────────────────────────────────────────────────────────

{provider_setup}


# ── Helper functions ───────────────────────────────────────────────────────────

def load_dataset(file_path: str) -> pd.DataFrame:
    """Load CSV or Excel file into a DataFrame."""
    ext = file_path.rsplit(".", 1)[-1].lower()
    if ext == "csv":
        df = pd.read_csv(file_path)
    elif ext in ("xlsx", "xls"):
        df = pd.read_excel(file_path)
    else:
        raise ValueError(f"Unsupported file type: .{{ext}}")

    if MESSAGE_COLUMN not in df.columns:
        raise ValueError(
            f"Column '{{MESSAGE_COLUMN}}' not found. "
            f"Available columns: {{list(df.columns)}}"
        )
    return df


def build_prompt(message_text: str) -> str:
    """Construct the full prompt for encoding one row."""
    codebook_block = ""
    for var in CODEBOOK:
        codebook_block += (
            f"- {{var['label']}} (type: {{var['type']}}): "
            f"{{var['definition']}}. "
            f"Allowed values: {{var.get('encoded_values', 'any')}}\\n"
        )

    prompt = f"""You are encoding one row of data. One row = one unit of observation.

## Experiment Instructions
{{EXPERIMENT_INSTRUCTIONS}}

## Encoding Instructions
{{ENCODING_INSTRUCTIONS}}

## Codebook Variables
{{codebook_block}}
## Message to Encode
{{message_text}}

## Output Requirements
- Return ONLY valid JSON
- Keys must exactly match the codebook labels: {{CODEBOOK_LABELS}}
- Each value must conform to the type and allowed values specified above
- Do not include any commentary, explanation, or markdown formatting
"""
    return prompt


def call_llm(prompt: str, max_retries: int = 3) -> dict:
    """Send prompt to the LLM and return parsed JSON response."""
    for attempt in range(1, max_retries + 1):
        try:
{provider_call}
            # Parse the response as JSON
            parsed = json.loads(response_text)
            return parsed
        except json.JSONDecodeError:
            # Try to extract JSON from the response
            text = response_text.strip()
            if text.startswith("```"):
                text = text.split("\\n", 1)[-1].rsplit("```", 1)[0].strip()
            try:
                parsed = json.loads(text)
                return parsed
            except json.JSONDecodeError:
                if attempt == max_retries:
                    print(f"  [ERROR] Failed to parse JSON after {{max_retries}} attempts")
                    return {{{", ".join(f'{json.dumps(l)}: None' for l in labels)}}}
                print(f"  [RETRY] Attempt {{attempt}}/{{max_retries}} - malformed JSON")
                time.sleep(1)
        except Exception as e:
            if attempt == max_retries:
                print(f"  [ERROR] API call failed: {{e}}")
                return {{{", ".join(f'{json.dumps(l)}: None' for l in labels)}}}
            print(f"  [RETRY] Attempt {{attempt}}/{{max_retries}} - {{e}}")
            time.sleep(2)

    return {{{", ".join(f'{json.dumps(l)}: None' for l in labels)}}}


def encode_dataframe(df: pd.DataFrame) -> pd.DataFrame:
    """Encode every row in the DataFrame using the LLM."""
    results = []
    total = len(df)

    for idx, row in df.iterrows():
        message = str(row[MESSAGE_COLUMN])
        if pd.isna(row[MESSAGE_COLUMN]) or message.strip() == "":
            print(f"  [{{idx + 1}}/{{total}}] Skipping empty row")
            result = {{{", ".join(f'{json.dumps(l)}: None' for l in labels)}}}
            result["_error"] = "empty_message"
        else:
            print(f"  [{{idx + 1}}/{{total}}] Encoding: {{message[:80]}}...")
            prompt = build_prompt(message)
            result = call_llm(prompt)

        result["_raw_response"] = json.dumps(result)
        results.append(result)

    # Add encoded columns to original DataFrame
    result_df = df.copy()
    for label in CODEBOOK_LABELS:
        result_df[label] = [r.get(label) for r in results]
    result_df["_raw_response"] = [r.get("_raw_response", "") for r in results]
    result_df["_error"] = [r.get("_error", "") for r in results]

    return result_df


def save_results(df: pd.DataFrame, input_path: str) -> str:
    """Save encoded results to a new CSV file."""
    base = input_path.rsplit(".", 1)[0]
    output_path = f"{{base}}_encoded.csv"
    df.to_csv(output_path, index=False)
    return output_path


# ── Main ───────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="LLM-based encoding of dataset rows")
    parser.add_argument("file", help="Path to CSV or Excel file to encode")
    args = parser.parse_args()

    print(f"Loading dataset: {{args.file}}")
    df = load_dataset(args.file)
    print(f"Loaded {{len(df)}} rows, encoding column: '{{MESSAGE_COLUMN}}'")

    print("Starting encoding...")
    result_df = encode_dataframe(df)

    output_path = save_results(result_df, args.file)
    print(f"\\nDone! Results saved to: {{output_path}}")
    print(f"  Rows processed: {{len(result_df)}}")
    print(f"  Codebook variables: {{", ".join(CODEBOOK_LABELS)}}")


if __name__ == "__main__":
    main()
'''
    return script


def _get_provider_code(provider: str) -> tuple[str, str, str]:
    """Return (import_block, setup_block, call_block) for the selected provider."""

    if provider == "openai":
        return (
            "from openai import OpenAI",
            'client = OpenAI(api_key=API_KEY)',
            '''            response = client.chat.completions.create(
                model="gpt-4o",
                messages=[
                    {"role": "system", "content": "You are a precise data encoder. Return only valid JSON."},
                    {"role": "user", "content": prompt},
                ],
                temperature=0.1,
                response_format={"type": "json_object"},
            )
            response_text = response.choices[0].message.content''',
        )
    elif provider == "anthropic":
        return (
            "import anthropic",
            'client = anthropic.Anthropic(api_key=API_KEY)',
            '''            response = client.messages.create(
                model="claude-sonnet-4-20250514",
                max_tokens=2048,
                system="You are a precise data encoder. Return only valid JSON.",
                messages=[{"role": "user", "content": prompt}],
            )
            response_text = response.content[0].text''',
        )
    elif provider == "gemini":
        return (
            "from google import genai",
            'client = genai.Client(api_key=API_KEY)',
            '''            response = client.models.generate_content(
                model="gemini-2.0-flash",
                contents=prompt,
                config={"system_instruction": "You are a precise data encoder. Return only valid JSON."},
            )
            response_text = response.text''',
        )
    elif provider == "deepseek":
        return (
            "from openai import OpenAI",
            'client = OpenAI(api_key=API_KEY, base_url="https://api.deepseek.com")',
            '''            response = client.chat.completions.create(
                model="deepseek-chat",
                messages=[
                    {"role": "system", "content": "You are a precise data encoder. Return only valid JSON."},
                    {"role": "user", "content": prompt},
                ],
                temperature=0.1,
            )
            response_text = response.choices[0].message.content''',
        )
    elif provider == "mistral":
        return (
            "from openai import OpenAI",
            'client = OpenAI(api_key=API_KEY, base_url="https://api.mistral.ai/v1")',
            '''            response = client.chat.completions.create(
                model="mistral-large-latest",
                messages=[
                    {"role": "system", "content": "You are a precise data encoder. Return only valid JSON."},
                    {"role": "user", "content": prompt},
                ],
                temperature=0.1,
            )
            response_text = response.choices[0].message.content''',
        )
    elif provider == "together":
        return (
            "from openai import OpenAI",
            'client = OpenAI(api_key=API_KEY, base_url="https://api.together.xyz/v1")',
            '''            response = client.chat.completions.create(
                model="meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8",
                messages=[
                    {"role": "system", "content": "You are a precise data encoder. Return only valid JSON."},
                    {"role": "user", "content": prompt},
                ],
                temperature=0.1,
            )
            response_text = response.choices[0].message.content''',
        )
    else:
        # Default to OpenAI-compatible
        return (
            "from openai import OpenAI",
            'client = OpenAI(api_key=API_KEY)',
            '''            response = client.chat.completions.create(
                model="gpt-4o",
                messages=[
                    {"role": "system", "content": "You are a precise data encoder. Return only valid JSON."},
                    {"role": "user", "content": prompt},
                ],
                temperature=0.1,
                response_format={"type": "json_object"},
            )
            response_text = response.choices[0].message.content''',
        )
